#controllers:
#    resource: ../../src/Controller/
#    type: annotation

app_orders_api:
    type: rest
    resource: \App\Controller\OrderController
    prefix: /api/orders
    name_prefix: app_api_order_
    defaults: { _format: json }